<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(PinqponqTargetFrameworks)</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <PackageId>Pinqponq.Sms</PackageId>
    <Title>Pinqponq SMS</Title>
    <Description>SMS gönderim davranışını (NetGSM) sarmalayan gönderim paketi. Standart ISmsSender arayüzü.</Description>
    <PackageTags>$(PackageTags);sms;netgsm;messaging;notification;sms-sender</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Polly.Core" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

</Project>
