<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Pinqponq.Identity.Otp/Pinqponq.Identity.Otp.csproj" />
    <ProjectReference Include="../../src/Pinqponq.Sms/Pinqponq.Sms.csproj" />
    <ProjectReference Include="../../src/Pinqponq.Mail/Pinqponq.Mail.csproj" />
  </ItemGroup>

</Project>
