<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(PinqponqTargetFrameworks)</TargetFrameworks>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Pinqponq.Identity.Otp/Pinqponq.Identity.Otp.csproj" />
    <ProjectReference Include="../../src/Pinqponq.Sms/Pinqponq.Sms.csproj" />
    <ProjectReference Include="../../src/Pinqponq.Mail/Pinqponq.Mail.csproj" />
  </ItemGroup>

</Project>
