<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(PinqponqTargetFrameworks)</TargetFrameworks>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Pinqponq.Auth.Sso.Abstractions/Pinqponq.Auth.Sso.Abstractions.csproj" />
  </ItemGroup>

</Project>
