<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(PinqponqTargetFrameworks)</TargetFrameworks>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Livekit.Server.Sdk.Dotnet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Pinqponq.LiveKit.Server/Pinqponq.LiveKit.Server.csproj" />
  </ItemGroup>

</Project>
